from catalog.tests.factories_tests.author_factory_test import AuthorFactoryTestCase
from catalog.tests.factories_tests.book_factory_test import BookFactoryTestCase
from catalog.tests.factories_tests.genre_factory_test import GenreFactoryTestCase
from catalog.tests.factories_tests.relationship_book_author_factory_test import RelationshipBookAuthorTestCase
from catalog.tests.factories_tests.relationship_book_genre_factory_test import RelationshipBookGenreTestCase
