# Generated by Django 4.0.2 on 2022-02-09 20:10

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('Pseudonymous', models.CharField(blank=True, max_length=64, null=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('mother_tongue', models.CharField(blank=True, choices=[('European Languages ', (('FR', 'French'), ('ES', 'Spanish'), ('PT', 'Portuguese'), ('DE', 'German'), ('EL', 'Greek'))), ('Asian Languages', (('RU', 'Russian'), ('ZH', 'Chinese')))], max_length=2, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('summary', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=16, unique=True, verbose_name='ISBN')),
                ('publish_year', models.DateField(blank=True, null=True)),
                ('original_language', models.CharField(choices=[('European Languages ', (('FR', 'French'), ('ES', 'Spanish'), ('PT', 'Portuguese'), ('DE', 'German'), ('EL', 'Greek'))), ('Asian Languages', (('RU', 'Russian'), ('ZH', 'Chinese')))], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipBookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(through='catalog.RelationshipBookAuthor', to='catalog.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='catalog.Genre'),
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(through='catalog.RelationshipBookAuthor', to='catalog.Book'),
        ),
    ]
