# Generated by Django 4.0.2 on 2022-02-09 20:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('status', models.CharField(choices=[('Available', 'Ava'), ('Borrowed', 'Bor'), ('Reserved', 'Res'), ('LOST', 'Los')], default='Available', max_length=10)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('num_borrowed', models.PositiveIntegerField(blank=True, null=True)),
                ('loan_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('prologue', models.TextField(blank=True, null=True)),
                ('edition_year', models.DateField()),
                ('edition_num', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.book')),
                ('prologue_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.author')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.publisher')),
            ],
            options={
                'ordering': ['return_date'],
            },
        ),
    ]
