# Generated by Django 4.0.2 on 2022-02-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_publisher_bookinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mother_tongue',
            field=models.CharField(blank=True, choices=[('European Languages ', (('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish'), ('PT', 'Portuguese'), ('DE', 'German'), ('EL', 'Greek'))), ('Asian Languages', (('RU', 'Russian'), ('ZH', 'Chinese')))], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_language',
            field=models.CharField(choices=[('European Languages ', (('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish'), ('PT', 'Portuguese'), ('DE', 'German'), ('EL', 'Greek'))), ('Asian Languages', (('RU', 'Russian'), ('ZH', 'Chinese')))], max_length=16),
        ),
    ]
